function fig = population_names_figure()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

% load population_names_figure
waitALittle;
load baps4
h0 = figure('Color',[0.8 0.8 0.8], ...
    'Colormap',mat0, ...
    'CloseRequestFcn','plotflow cancel_pop_name', ...
	'MenuBar','none', ...
	'Name','Cluster Names', ...
	'NumberTitle','off', ...
	'Position',[533 448 365 197], ...
    'Resize','off', ...
	'Tag','population_names_figure');
h1 = uimenu('Parent',h0, ...
	'Label','Files', ...
	'Tag','input_pop_name_file_menu');
h2 = uimenu('Parent',h1, ...
	'Callback','plotflow load_pop_names', ...
	'Label','Load Names', ...
	'Tag','load_pop_names_menu');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','plotflow cancel_pop_name', ...
	'ListboxTop',0, ...
	'Position',[122.25 12 59 19], ...
	'String','Cancel', ...
	'Tag','cancel_pop_name_button');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','plotflow ok_pop_name', ...
	'ListboxTop',0, ...
	'Position',[192.75 12 59 19], ...
	'String','Ok', ...
	'Tag','ok_pop_name_button');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.753 0.753 0.753], ...
	'ListboxTop',0, ...
	'Position',[18.75 47.25 233.25 82.5], ...
	'Style','frame', ...
	'Tag','input_pop_name_frame');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.753 0.753 0.753], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[30.75 107.25 203.25 13.5], ...
	'String','Name of Cluster 1:', ...
	'Style','text', ...
	'Tag','input_pop_name_text');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','plotflow edit_pop_name', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[32.25 86.25 201.75 17.25], ...
	'Style','edit', ...
	'Tag','pop_name_edit');
h1 = uicontrol('Parent',h0, ...
	'FontWeight','bold', ...
    'Units','points', ...
	'Callback','plotflow five_back', ...
	'ListboxTop',0, ...
	'Position',[159.75 60 15 15], ...
	'String','<<', ...
	'Tag','five_back_button');
h1 = uicontrol('Parent',h0, ...
    'FontWeight','bold', ...
	'Units','points', ...
	'Callback','plotflow one_back', ...
	'ListboxTop',0, ...
	'Position',[179.25 60 15 15], ...
	'String','<', ...
	'Tag','one_back_button');
h1 = uicontrol('Parent',h0, ...
    'FontWeight','bold', ...
	'Units','points', ...
	'Callback','plotflow one_ahead', ...
	'ListboxTop',0, ...
	'Position',[199.5 60 15 15], ...
	'String','>', ...
	'Tag','one_ahead_button');
h1 = uicontrol('Parent',h0, ...
    'FontWeight','bold', ...
	'Units','points', ...
	'Callback','plotflow five_ahead', ...
	'ListboxTop',0, ...
	'Position',[219.75 60 15 15], ...
	'String','>>', ...
	'Tag','five_ahead_button');
if nargout > 0, fig = h0; end
